### ISSUE TITLE
Hide skipped songs in pleblist

### ISSUE THREAD

**Issue by Nacht123** [pajlada/pajbot#114]
Add a new row to __tb_pleblist_song__ with maybe the name __skipped__ 

__0/null/none = not skipped__

__1 = skipped__

with this we could hide the skipped song.

__edit__

hide the vod link of the song if its more than 10 minutes
 ```
{% if song.song_info.duration <= '600' %}
```
get this before the vod link thing

**Comment by pajlada** [comment]
The "hide vod link if song is more than 10 minutes" has been implemented in 7f9c9ba89010709870c1eeb67c2d83aa9cc56b16

**Comment by Nacht123** [comment]
found a "bug"

if we get a stream_chunk with video url __NULL__ it should not be shown on the page
here a fix
> [Old file edit to new file](https://gist.github.com/Nacht123/594a846e968299022dd9/revisions)




and there is a cache __error__ it doesn't refresh the __stream_chunk databse__ for the video url :imp: 
> https://forsen.tv/pleblist/history/25/ 

no url because there is somewhere a cache or no update FeelsBadMan

**Comment by pajlada** [comment]
@Nacht123 The bugs mentioned in the most recent post should have been fixed. Let me know if you believe this is not the case.
Still considering how we should/if we should implement the skipped column
