### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by dinubish** [pajlada/pajbot#120]
Hello! Pajlada,
I'm getting this error when i try to run the bot, i did everything is asked in the wiki
https://dinubish.xyz/db-792-l.png
Can you please help me fix it.
Thanks

**Comment by pajlada** [comment]
helped him out in my twitch chat instead.
The solution was to use `pip3 install` instead of `pip install`

**Comment by KostasPelelis** [comment]
Also consider using a virtual environment for python > 3 http://stackoverflow.com/a/23842752. Python's backward compatibility is really bad especially after the python 3 upgrade
