### ISSUE TITLE
More detailed installation instructions (PM2, nginx, uwsgi)

### ISSUE THREAD

**Issue by Nacht123** [pajlada/pajbot#123]
From twitch chat two days ago
`02:22 RiTu1337: @pajlada, can you git your nginx site config sometimes and other related shit`

Whould be nice if there would be an overview about this stuff. 
`nginx` `PM2` idk if there are more stuff :package:

**Comment by dinubish** [comment]
i need the nginx config too :(

**Comment by pajlada** [comment]
Nginx config for forsen.tv: https://gist.github.com/pajlada/ed7d549c57501da29938
Along with the UWSGI config I use

**Comment by Nacht123** [comment]
*(i stole code from the stream VODs :walking: )*<br/>
I updated the **Install Guide** for
- [PM2](/pajlada/pajbot/wiki/Installation-Bot#7-pm2-guide-optional)
- [nginx](/pajlada/pajbot/wiki/Installation-Website#7-nginx-optional)
- [uWSGI](/pajlada/pajbot/wiki/Installation-Website#6-uwsgi-guide-optional)

It should work, to run the bot on **Ubuntu 15.10** or **Debian 8.3**<br/>
Not on **Ubuntu 14.04.4** since there is no systemctl.

I used the gist link and changed some things to run it as *pajbot* not *forsen*


It's a basic Guide and you need to config the details yourself.
