### ISSUE TITLE
Move Raffle functionality to a module

### ISSUE THREAD

**Issue by polle-vanhoof** [pajlada/pajbot#125]
Title says it all, move the Raffle functionality to a module instead of dispatch.py

**Comment by ManikDV** [comment]
I agree. It will be simplier if we put all logic related to raffle, https://github.com/pajlada/pajbot/issues/132 and future complex commands into separate modules. @pajlada , what do u think?

**Comment by polle-vanhoof** [comment]
Also, as paj mentioned on stream, add settings command to choose a percentage of users that win the raffle instead of 1 person. (reminder to self: round up so no 0 winners rofl)

**Comment by pajlada** [comment]
@ManikDV Yes, each feature like that should most definitely be stored in separate modules.

**Comment by pajlada** [comment]
As for implementation details, here's some information about how I want the raffles to work:

For basic raffles, you should be able to use `!raffle 200` to create a 200-point raffle that lasts for 60 seconds (could be configurable in the settings).
To create a custom-timed raffle, you should use `!raffle 200 20` where the second integer is the amount of seconds the raffle should run for.
The amount of notifications about a running raffle should be "dynamic".
For a 15-second raffle, there should be maybe 1 notification when 5 seconds left.
For a 30 second raffle, notify on 20 and 10 seconds left.
For a 60 second raffle, notify of 45, 30, 15 seconds left.
For anything above 120 seconds, notify on each whole minute.

**Comment by polle-vanhoof** [comment]
Should there be a maximum/minimum to the time that can be entered for the raffles? like no 1 second raffles or no 1 month raffles?

**Comment by pajlada** [comment]
Probably yeah. Minimum duration 5 seconds, maximum duration 3600 seconds?

**Comment by pajlada** [comment]
Base move done in f1de6a9364f01fa19c71d5f75486b771fbf6a139

**Comment by pajlada** [comment]
Fully implemented, thanks guys <3
