### ISSUE TITLE
Add multistream command

### ISSUE THREAD

**Issue by wallrik** [pajlada/pajbot#133]
I don't always use multistream pages, but when I do, I use http://multistre.am/ ![SeemsGood](https://static-cdn.jtvnw.net/emoticons/v1/64138/1.0)
Simple request, can we have a `!multi2` command that works just like `!mutli`? ![MingLee](https://static-cdn.jtvnw.net/emoticons/v1/68856/1.0)

URL's look the same: http://multistre.am/forsenlol/reckful

**Comment by pajlada** [comment]
:+1: Seems good.

I'm considering whether this should be a module, or a filter for a normal command.

So you could do like this:

`!add command multi http://multistre.am/$(args|join('/'))`

Any feedback on the options is greatly appreciated

**Comment by pajlada** [comment]
Fixed in f6b9798b6972bd418c1cf41100bf8e87467203f5
