### ISSUE TITLE
Chat Highlights-Sticky Chat

### ISSUE THREAD

**Issue by KostasPelelis** [pajlada/pajbot#135]
You can add a moderator command like !chatsave X which will save the previous X lines of chat but I guess that would require some caching. Also something an event driven command like !remindme {time} {message} would be useful. Great work though pajlada. Your project is inspiring

**Comment by pajlada** [comment]
Could you give me some usage examples for !chatsave?
Like what it could be useful for?

As for !remindme, there's already a remindme command (it's currently in dispatch.py though, it could be moved to a module. It also doesn't persist through bot restarts, which could be neat.

**Comment by KostasPelelis** [comment]
1) A memefest goes on and a moderator wants to save the highlight image(I guess it can be created using the text) to the website.
2) Capture more drama SaltyCorn
3) A dank duel/raffle which resulted Karl_Kons go over 0 points
4) A link/song someone posted and you cant copy because forsenWut

As for the remind me command it is moderator only (which shouldn't :P ) and I think it should work with dates as well

**Comment by pajlada** [comment]
Closing this issue as I don't feel it would fit into the current scope of pajbot.
