### ISSUE TITLE
Logs in admin panel

### ISSUE THREAD

**Issue by gigglearrows** [pajlada/pajbot#138]
Would be a great idea to put logs from chat in the admin panel on the website. Moderators can then check logs if there was an event or something that needs clarification. Logs of what that person has been saying, just not that day but a couple of weeks earlier too. So mods dont ban someone that's actually nice and talkative.

**Comment by pajlada** [comment]
Logs is something I want to implement, not quite sure how to store last messages of a user.
One possibility is this:
Store a log element for each time a user is timed out (the CLEARCHAT event is thrown).
When that is thrown, we store the users latest message along with the timeout row in the database.
I also want logs for admin commands like, whenever someone uses `!add command` it should be visible in the logs properly.

I'm thinking logs should be stored in MySQL under `tb_log` or something like that.
Not sure about the structure yet.

**Comment by gigglearrows** [comment]
ye, also recent changes and which mod who changed anything

**Comment by pajlada** [comment]
- [ ] Command removed
 - [ ] Command added
 - [ ] Command edited
 - [ ] Banphrase removed
 - [ ] Banphrase added
 - [ ] Banphrase edited
 - [ ] Blacklisted link added
 - [ ] Blacklisted link removed
 - [ ] Whitelisted link added
 - [ ] Whitelisted link removed
 - [ ] Timer removed
 - [ ] Timer added
 - [ ] Timer edited
 - [ ] Userlevel edited
 - [ ] Module removed
 - [ ] Module added
 - [ ] Module edited
 - [ ] Permaban removed
 - [ ] Permaban added
 - [ ] Game set
 - [ ] Title set

Log entry layout:
```json
{
    "message": "XD",
    "tag": "Command edited",
    "created_at": "2015-09-13 12:03:04",
    "added_by": 123,
    "data": {
        "previous_command": "xd",
        "new_command": "XD",
    }
}

```

**Comment by Nacht123** [comment]
logs for 
- [ ] !add alias
- [ ] !remove alias
