### ISSUE TITLE
lottery system

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#147]
!lottery start - Start a lottery.
!lottery end - Ends a lottery. Claims a winner
!lottery join 100 - Joins a lottery with 100 tickets (costs 100 points)
!lottery 100 - aliased to join

**Comment by ManikDV** [comment]
So, if one user pays 100 points and the second pays 200, it means that the second one has twice as much probability to win?

**Comment by pajlada** [comment]
Yes

**Comment by ManikDV** [comment]
@pajlada I think we can close it.

**Comment by pajlada** [comment]
@ManikDV Thank you
