### ISSUE TITLE
Transfer pleblist songs to new pleblist if they haven't been played

### ISSUE THREAD

**Issue by Destroyer** [pajlada/pajbot#162]
I think if someone donates in order to get his song played he should get it, even if pleblist gets switched  off before all songs are played. When next stream starts, it should check previous pleb list and copy songs that haven't been played to a new one.

**Comment by pajlada** [comment]
This can be a bit tricky getting 100% accurate.
Sometimes, there's just a song at the end that got played like 90% before he stopped the pleblist, and I wouldn't want that song to be added to the next pleblist.
Maybe all but the "first" of the unplayed songs?

**Comment by Destroyer** [comment]
I'm not sure how it's handled in code but videos have 3 states from what I can see in pleblist - played already, currently playing, will be played. Only those that are in state will be played (have white background) would be copied. But if you can't rely on that then the option all after "first" unplayed is the way to go.

**Comment by pajlada** [comment]
For the time being, I'm going to close this issue.
It's way too complex as it is right now.

In case the stream goes down for like 10 minutes, and then comes up again, a new stream will have been created in the database.
This means all songs that are _currently_ playing will be duplicated into the "new stream", which will fuck things up.

The easiest solution is just to manually re-added the one or two songs that weren't played from the day before in the **client** page's "manual input box".
