### ISSUE TITLE
Teach bot to respond command in private messages

### ISSUE THREAD

**Issue by 1fmn1** [pajlada/pajbot#163]
Somtimes it's impossible to read chat because of spam. Please make the option to type bot commands in private.

**Comment by pajlada** [comment]
Is there any command in particular you want this enabled on?

The functionality already exists, it's just a matter of toggling it per command.

**Comment by 1fmn1** [comment]
Like !quest, !followage, !tokens. Sometimes it's just impossible to find out, what quest do we have today :)

**Comment by 1fmn1** [comment]
Ok, I see bot answers commands that written in private, he writes answers to the main chat, but why? Why not in private?
