### ISSUE TITLE
Resetting negative Points

### ISSUE THREAD

**Issue by Coreblade** [pajlada/pajbot#171]
Please add the Possibility for Mods to reset negative Points. (it happened to me by accident (-10mil atm at reipbot)

**Comment by Nacht123** [comment]
Don't join negative raffles :-1: , you can't never do it "by accident"


Maybe a **max negative points** on raffles, so mods can't fuck it up to much
and a  **max negative points** on bingo


I still don't get it why people would join a negative raffle :palm_tree:

**Comment by Coreblade** [comment]
it can happen by accident if u only read "raffle" and type join realizing after u sent that that ur in a -10 mil points raffle... but that negative point thing isn't good i think .. there should only be positive raffles and stuff..
