### ISSUE TITLE
ALL IN

### ISSUE THREAD

**Issue by coral** [pajlada/pajbot#177]
!roulette should have a commando called ALL IN that just roulettes all your point, example:

```
!roulette ALL IN

pajbot: coral has lost 10000000 points
```

**Comment by gempir** [comment]
+1 or just !allin

**Comment by Ian321** [comment]
+1 or !coral Keepo

**Comment by T-Brawl** [comment]
#178

**Comment by coral** [comment]
smoke weed everyday

**Comment by pajlada** [comment]
Fixed in 868733ddb92ef907c235bcb89c68590f81c8e5f1

I decided against !allin and just went with !roulette all. Perhaps make it listen to !roulette allin too
