### ISSUE TITLE
Show donation links in twitch chat

### ISSUE THREAD

**Issue by CraigBanach** [pajlada/pajbot#186]
Add a feature to snusbot so that links given to streamers in donations are pasted into twitch chat for easy clicking. 

The most difficult part of this will probably be reading the donation link from a twitch stream. Once that is done then parse it and get snusbot (etc.) to post it in chat for the plebs to click.

**Comment by Nacht123** [comment]
This can't work, **snusbot** and **Forsen** would get banned when a **mod** is spamming **VIRUS** or **NSFW** links.


My tip get a screenshot **hotkey** or watch the **vod**.

**Comment by joaopms** [comment]
Maybe this can be turned into a command? After the host opens the link, runs a command like `!share` and the link goes to the cat.

**Comment by pajlada** [comment]
As @Nacht123 said, there are too many edge cases. I wouldn't even want to show all links on the website unfiltered.
