### ISSUE TITLE
Make it possible to do a quest multiple times

### ISSUE THREAD

**Issue by th0mk** [pajlada/pajbot#200]
If a quest like 'Win 500 points in a raffle' has been completed then it should be possible to do the quest again, but then with it being twice (or more) as difficult. To prevent giving out too many tokens you could maybe lower the token reward, make it sub only or something else.

**Comment by pajlada** [comment]
I don't want to implement this, not with the system being like it is right now.
I believe it would be too difficult for me to balance costs for things, such as !#playsound. It's already difficult as it is.
