### ISSUE TITLE
#showemote cannot see emotes from channels that no longer have sub button?

### ISSUE THREAD

**Issue by dadozer** [pajlada/pajbot#208]
Maybe this isn't even a bug on your end, i dunno.
But this is what happened with the donation complaining about showemote not working - i talked to the guy ad figured out the problem, i think.

So the emote in question belongs to this channel. Here is the twitchemotes page:
https://twitchemotes.com/channel/thepremierleague

When you go to their twitch page now, you will see that they no longer have a sub button.
The guy was definitely still able to use the emotes though, and I was not.
I'm not even sure how these emotes still exist but for some reason the bot can't detect them properly.
http://imgur.com/KBmBhOL part of the chat log.

**Comment by pajlada** [comment]
Fixed, thanks for the valuable bug report!
