### ISSUE TITLE
Highlight changes

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#209]
- [x] Add a "added_by" column, foreign_key to tb_user.id. Default null
 - [x] Make it possible to have !add highlight as a command available for subs.
 - [x] This means we should move the majority of the functionality into a module, which we can configure on the fly.

**If subs can use it.**
- [ ] **Filter** for highlight names (no links allowed and maybe some words are blocked/banned)
- [ ] **Blacklist** for User's who abused it or different level or something :)

**Comment by Nacht123** [comment]
**If subs can use it.**
- [ ] **Filter** for highlight names (no links allowed and maybe some words are blocked/banned)
- [ ] **Blacklist** for User's who abused it or different level or something :)

**Comment by pajlada** [comment]
Improve the `!edit highlight` response in case --id is missing.
"Did you mean to create a new highlight? In that case, use !add highlight instead!"

**Comment by Destroyer** [comment]
- [ ] Automatically remove highlights from the page if they're older than 2months as they're not stored by twitch ( http://blog.twitch.tv/2014/08/update-changes-to-vods-on-twitch/ ). Second option would be to be able to create regular highlight but I don't think there's an API for that
