### ISSUE TITLE
Reckful soundboard

### ISSUE THREAD

**Issue by Sephironx** [pajlada/pajbot#229]
its not a lie: https://clyp.it/bka5dgib

I'm not fucking lying: https://clyp.it/sxdwikv0

Lost in the sauce: https://clyp.it/me0yvrl2

Team time with Byrone: https://clyp.it/vak1flhz

GAMBAA: https://clyp.it/1sylngsz

**Comment by dextermb** [comment]
Why would you _want_ a reckful soundboard? I don't even think that reckful uses pajlada's bots
