### ISSUE TITLE
New name for raffle's

### ISSUE THREAD

**Issue by Nacht123** [pajlada/pajbot#234]
Since we most of the time use **multiraffle**,

i hate to type **multi** always.

How about

```sh
# old
!multiraffle

#new
!multiraffle
!mraffle

# maybe if multiraffle module active
!raffle
```

```sh
# old
!raffle

#new
!singleraffle
!sraffle
```

something like this, not sure what exactly about `!raffle` if only multi or still a single raffle.

**Comment by dextermb** [comment]
For multiraffle
```
!raffle -m
```

For single raffle
```
!raffle
```

I would prefer this solution

**Comment by NotDefendotKappa** [comment]
How about just !multi Keepo no ones gonna see you type it anyway(if its in forsens channel)

**Comment by pajlada** [comment]
I'd prefer to leave !multi open for another command

**Comment by gempir** [comment]
I think this can be closed !mraffle and !sraffle is a good solution
