### ISSUE TITLE
riotwatcher: python setup.py egg_info (Failed) when running: ./install/venvinstall.sh

### ISSUE THREAD

**Issue by kyroskoh** [pajlada/pajbot#239]
Collecting riotwatcher (from -r pip-requirements.txt (line 30))
  Using cached riotwatcher-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eb5tuatm/riotwatcher/setup.py", line 15, in <module>
        long_description=open(descr_file).read(),
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8308: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eb5tuatm/riotwatcher/

**Comment by Nacht123** [comment]
It's something on your side **not pajbot**
<hr>
Whats your **operating system**?
Did you do it after this [__Guide__](/pajlada/pajbot/wiki/Installation-Bot) or did you **change something?**
<hr>
_I could install riotwatcher without any error's on a new Ubuntu 15.10_
```sh
ubuntu@ubuntu:/srv/pajbot$ sudo apt-get install python3.4-venv

ubuntu@ubuntu:/srv/pajbot$ ./install/venvinstall.sh
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-8.1.0-py2.py3-none-any.whl#md5=c6eca6736b2b8f7280fb25e44be7c51b
  Downloading pip-8.1.0-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
Collecting riotwatcher (from -r pip-requirements.txt (line 30))
  Downloading riotwatcher-1.3.2.tar.gz
Collecting requests (from riotwatcher->-r pip-requirements.txt (line 30))
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 501kB 2.2MB/s 
Installing collected packages: requests, riotwatcher
  Running setup.py install for riotwatcher ... done
Successfully installed requests-2.9.1 riotwatcher-1.3.2
```
<hr>
Maybe try to `delete` the `myvenv` folder and run it again.
<hr>
or change the **pip-requirements.txt** file, to see if its riotwatcher.

```
riotwatcher
```
to
```
# riotwatcher
```
<hr>
Maybe your cached `version` is just broken.

**Comment by GrappigPanda** [comment]
I feel like this is one of those instances where you want definite required versions. @pajlada, I'm imaging if you ran `pip freeze`, you wouldn't have riotwatcher v1.3.2. Is there any reason you don't enforce specific versions?

**Comment by pajlada** [comment]
I like new stuff lol that's it. Might not be smart though

**Comment by Nacht123** [comment]
Closing this issue, since there is no response from the creator. :zap:
