### ISSUE TITLE
!roulette % values

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#241]
!roulette 50% to bet 50% of your points

**Comment by KostasPelelis** [comment]
The % character is a bit tricky. You can avoid it by using decimal percentage like 0.5 or if you don't want to use the dot use a comma like 0,2 for 20% of the points

**Comment by pajlada** [comment]
Why is the % character tricky?
I could just, before I cast it to an int check if the last character is %
like this:
```python
if msgparts[0].endswith('%'):
  percentage = max(0, min(100, int(msgparts[0][:-1])))
  value = user_points * (percentage / 100)
else
  value = int(msgparts[0])
```

**Comment by KostasPelelis** [comment]
I guess it is more of a protocol thing rather than trickiness. The % character is treated as NUL if I am not mistaken therefore it shouldn't be permitted in IRC based chats.
