### ISSUE TITLE
Suggestion: post youtube/imgur links from donations somewhere

### ISSUE THREAD

**Issue by madfriend** [pajlada/pajbot#245]
There are times where Forsen opens links and genuinely laughs at them, but can't show them on stream; it would be nice to be able to check them.

**Comment by dextermb** [comment]
Certainly a good idea, how about a `!recent` command that whispers the user the donation text (if a _allow recent command_ checkbox is checked when the donation is sent?)

**Comment by Nacht123** [comment]
Same as #186

It's **not possible** without getting __Forsen__ or __Snusbot__ banned in the long view.
There are just too many stupid links.

**Even if it will get whispered.**

Better take a **screenshot / oddshot / watch vod** or something equal, to get the link.

**Comment by madfriend** [comment]
My original idea was about posting to dedicated section of forsen.tv (where the pleblist lives). I did not propose to post links in chat or whisper them.

**Comment by Nacht123** [comment]
Same issue on forsen.tv, you just **don't want some links**.
It could flag **forsen.tv** as a **virus domain** :hammer: 

From the other issue **186**

```
# pajlada
I wouldn't even want to show all links on the website unfiltered.
```
