### ISSUE TITLE
Wowsobot no longer responding to commands, possibly due to twitch chat server move

### ISSUE THREAD

**Issue by mosukiton** [pajlada/pajbot#247]
I'm not sure if you are already aware, but Twitch is in the process of moving their servers from "irc.twitch.tv" to "irc.chat.twitch.tv". https://discuss.dev.twitch.tv/t/psa-chat-servers-are-going-to-migrate-to-aws-ec2-servers/4877

I thought I should let you know just in case, since wowsobot has stopped responding to commands. I believe the server move to be the case as I was only able to access imaqtpie's chat on "Chatty" (external twitch chat program), after changing the server address.

**Comment by pajlada** [comment]
Thanks, fixed
