### ISSUE TITLE
new token based command !#sendmessage

### ISSUE THREAD

**Issue by CodeBowser** [pajlada/pajbot#254]
What about making a token based command (for like 10 tokens) that send a message directly to forsen, like donations do? Because some people really can't afford sending 3$ everytime he didn't understands something or if you want to tell him something that nobody else should see.

**Comment by gempir** [comment]
10 tokens wouldn't be enough for this IMO. Forsen would have to deal with another row of messages and 10 tokens are easily farmed.

**Comment by joaopms** [comment]
Maybe 50/100 tokens and only one message per month?

**Comment by gempir** [comment]
the limit of 1 per month might be a really good idea. Although 50 tokens would be a lot. Maybe limit to 1 message every 2 weeks and costing ~25 tokens, this would be possible when there is a max limit of tokens and not how it currently works.

Although this is generally a bigger feature where pajlada has to decide if he wants that in his bot.

**Comment by pajlada** [comment]
I don't think I want to risk including this. Too many holes. Closing it for now.
