### ISSUE TITLE
Is roulette actually broken ? (Half-serious post EleGiggle)

### ISSUE THREAD

**Issue by T-Brawl** [pajlada/pajbot#266]
Indeed, I'm genuinely striked by the losing run I had the last threee days. 

My ratio was normal (slighty above 45%, so around the win ratio) until I've only won 11 out of my 45 tries (24,44%) including 7 losses in a row (probablity of 1.5% that happens) and the day later 8 losses in a row (**0.83% !**). That 8 losses streak is still alive though, it's just I don't have any points to try again Kappa

I mean, what are the odds to be fine for months and then be insanely unlucky and break his personal record two times in two days? Did someone hack the `rigged_random_result()` or what? Did Athene bots generate negative numbers to troll me? FeelsBadMan

**Comment by gempir** [comment]
Roulette more and your percentage will get closer to what its set in the bot.

Basic mathematics, you are just a bit unlucky

**Comment by T-Brawl** [comment]
Yeah definitely, that's even why I've started by saying my ratio was normal since it was above of the winning ratio (45.6 iirc). [The more I roll, the more my ratio would be close to 45%](https://en.wikipedia.org/wiki/Law_of_large_numbers). However my ratio is still around 45% (44.8) but for how long FeelBadMan 

Well I guess I'm BabyRaging too much

**Comment by pajlada** [comment]
yep :sunglasses:
