### ISSUE TITLE
Roulette history updates before total points

### ISSUE THREAD

**Issue by dextermb** [pajlada/pajbot#273]
![Out of sync](https://cloud.githubusercontent.com/assets/6137789/14158084/2c8a6f8a-f6c6-11e5-8b50-214473d6cf4c.png)

![Userpoints in chat](https://cloud.githubusercontent.com/assets/6137789/14158099/3f920c82-f6c6-11e5-9c49-0619175cd77b.png)

I had 23658 and gambled 3658; history updated but total points doesn't until a while later... fix pl0x

:tophat: :briefcase:

**Comment by gempir** [comment]
Userdata is update every 10 minutes. Roulette stats are updated instantly, IIRC. This a little weird behaviour, but not "bugged".

Since pajlada is already reworking the user system, this will probably change anyway.

**Comment by Nacht123** [comment]
Points are live now, it was fixed here 46c5b9d98ab2e5616c2b63981a18f72afb9676e0
