### ISSUE TITLE
forsen.tv/commands raffle/multiraffle examples mistake

### ISSUE THREAD

**Issue by Ampzyh** [pajlada/pajbot#274]
On the commands page for the bots, the command example's for !multiraffle and !raffle include the word "in" twice unnecessarily as shown in the gyazo. "The raffle will end in in" Keepo
![](https://i.gyazo.com/76c9f47b49f77c058edec03d28e70b55.png)

**Comment by dextermb** [comment]
> Grammatical error in raffle command example

Nice find!

:tophat: :briefcase:
