### ISSUE TITLE
New layout for /admin/banphrases/ (unwanted hidden options)

### ISSUE THREAD

**Issue by Nacht123** [pajlada/pajbot#275]
If you goto https://forsen.tv/admin/banphrases/

The site is **broken** because of long links ( facebook, reddit etc.) and too many stuff for one row.

You **can't** even **scroll**  (hidden stuff on the right) on the website (this problem was always there),
if it's not fullscreen.

Maybe change the layout in **two rows** like commands.

It maybe works on 1440p but not on 1080p
![1080](http://i.imgur.com/qO5EOFi.png)

**Comment by dextermb** [comment]
Love the arrow. Keep up the good work!

:tophat: :briefcase:
