### ISSUE TITLE
Pleblist button to scroll down to current song

### ISSUE THREAD

**Issue by Dankeroni** [pajlada/pajbot#280]
![pleblisterino](https://cloud.githubusercontent.com/assets/16510338/14363506/ed6e86c0-fd04-11e5-9407-eb846430fa0d.PNG)

**Comment by dextermb** [comment]
For smooth scrolling:

```
$(".scrollToActive").on('click', function() {
    $('html, body').animate({
        scrollTop: $(".currentSong").offset().top
    }, 1000);
});
```

If the button is an anchor tag:

```
$(".scrollToActive").on('click', function(e) {
    $('html, body').animate({
        scrollTop: $(".currentSong").offset().top
    }, 1000);
    e.preventDefault();
});
```

:tophat: :briefcase:

**Comment by pajlada** [comment]
You can click the "link" button to the left of that (http://i.imgur.com/C1SZTjA.png) to get to the current song.

**Comment by Dankeroni** [comment]
@pajlada There should be a button that scrolls down to the current song in the playlist, maybe next to the link button.

**Comment by Dankeroni** [comment]
@pajlada I just noticed that button LUL
