### ISSUE TITLE
New playsounds for the stream

### ISSUE THREAD

**Issue by otul** [pajlada/pajbot#283]
I'll leave you here a few missing gachi sounds for the playsound command. You can add them if you want :)

https://mega.nz/#!58V2USqC!A5J8LUTCGQR8JSc1-yxoTkHsLJXR-prnTbxJmg4lC8w

**Comment by dextermb** [comment]
Should be posted in #155 

:tophat: :briefcase:

**Comment by otul** [comment]
Oh shit, I'm sorry.
