### ISSUE TITLE
Earn 50% of online points, offline

### ISSUE THREAD

**Issue by dextermb** [pajlada/pajbot#287]
I would like to be able to still earn points offline, 50% of online points (rounded downwards if points are stored as an INT)

> Subscribers gain 5 points per 5 minutes while watching the stream.
> Non-subscribers gain 1 point per 5 minutes while watching the stream.

.

> Subscribers gain 2.5 points per 5 minutes while the stream is offline.
> Non-subscribers gain 0.5 points per 5 minutes while the stream is offline.

:tophat: :briefcase:

**Comment by Nacht123** [comment]
Points for people who run the pc for 24h ?

Not the best idea.
The points are there, that you watch the stream and not for offline lurker :ghost:

**Comment by dextermb** [comment]
:facepunch: Give me my offline points

:tophat: :briefcase:

**Comment by pajlada** [comment]
what @Nacht123  said, i don't want offline points.
