### ISSUE TITLE
[Idea] Pay points for a message on stream or a token

### ISSUE THREAD

**Issue by T-Brawl** [pajlada/pajbot#291]
I dunno if that idea was already submitted but what about spend points to display a message on stream (like a donation would do) or to buy tokens?

Of course, the price should be pretty high (at least 10K for one message/token? 50K? 69K? gachiGASM) or the spam would be a nightmare. Or maybe, only subs would be able to do.

**Comment by dextermb** [comment]
Interesting idea, definitely worth implementing as a module (that can be turned on or off)!

:tophat: :briefcase:

**Comment by Nacht123** [comment]
The points system is broken at the moment,
if there are **auto raffles** on subs and/or **roulettes** people can generate points.

Not sure if this can be used with points.

Tokens are easy too :cactus: 

And there is the **filter** problem,
you need a **big filter** like in streamtip to not show stupid stuff on stream.

**Comment by pajlada** [comment]
as nightnacht said, it would need too much filtering to make work. people _will_ find ways around a filter, leaving the streamer in an awkward position
