### ISSUE TITLE
Website minor bug

### ISSUE THREAD

**Issue by KostasPelelis** [pajlada/pajbot#297]
**Browse**: Chromium
**Operating System** Ubuntu Gnome Linux
 
**Bug Description** When selecting a command in the commands list (https://forsen.tv/commands/) and then going up in the list, selecting a new command doesn't update the UI

**Severity**: Minor

**Steps to Reproduce**

- Select a command on the bottom of the list
- Scroll Up
- Select a new Command

**Workaround** Select the command again

**Comment by Nacht123** [comment]
http://i.imgur.com/rDDnkk6.gifv
Works for me, did you do **something different** than me in this gif?
- Was it just **random** **or** does it **always** bugs for you? or
- maybe you just opened the command page, when the **server was slow** and it couldn't update it 
or
- some **chrome extensions** blocks it for you.

**Comment by KostasPelelis** [comment]
It seems to be working now. It was foolish of me not to check DevTools before submitting. Thanks for the heads up
