### ISSUE TITLE
[Idea] !hsarena

### ISSUE THREAD

**Issue by T-Brawl** [pajlada/pajbot#301]
I don't know exactly how the bot checks the Hearthstone statuis on streamer's computer but since Twitch has started an official 100-in-10 challenge, I think a module for betting the score is now relevant.

Of course, it needs some security like not being able to bet for a 69-420 score or 1.5-(-89) score. One problem would if a streamer has stopped a run at 4-2 for example and stops playing arena for a week (set a timeout then ?).

Yeah I know. I sumbit ideas, yet I only made 3 small commits for pajbot EleGiggle

**Comment by Nacht123** [comment]
There is already a [Predict](https://github.com/pajlada/pajbot/blob/master/pajbot/modules/predict.py) module for arena runs.

This **wouldn't work** very well with the hsbet system,
since there are to many games and
the streamer resets the arena run to often when he failed on a 1-3 run.

**Comment by T-Brawl** [comment]
Well if there is the predict module, I guess we don't need this issue anymore.

Case closed.
