### ISSUE TITLE
!$Playsound for plebs?

### ISSUE THREAD

**Issue by Bassofia** [pajlada/pajbot#312]
Is there any way I can make the command "!$playsound" available for everyone?

**Comment by Bassofia** [comment]
Got it, syntax problem lmao

**Comment by pajlada** [comment]
I'll make it a proper setting that you can modify in the web interface

**Comment by pajlada** [comment]
@Bassofia Fixed in 185169bf1494af2bd653ddba931c2fe95918e54a
