### ISSUE TITLE
Pajbot not giving points to non-subs every 5min

### ISSUE THREAD

**Issue by reorden** [pajlada/pajbot#323]
I've been runing the pajbot on my pc for 3 months now, but recently realised it was not giving the viewers 1point per 5min. Yeah it took me a while to realise that but well at least i did forsenE. Anyone has an idea what would be the reason for that? (can't test it for subs for obvious reasons)

**Comment by pajlada** [comment]
You need to either run the chatters microservice on the side, or remove a line in pajbots code: https://github.com/pajlada/pajbot/blob/master/pajbot/modules/chatters.py#L30

**Comment by reorden** [comment]
It's working, removed the line, thx man <3
