### ISSUE TITLE
Indefensible Ban

### ISSUE THREAD

**Issue by denniscoo** [pajlada/pajbot#335]
Hello, today as I logged into the stream to watch forsen, I realised as soon as I typer LUL that I was banned.
I am a 3 year old faithful follower, now to ruin that is unforgivable. Could you please revert this?

Thank you very much for your correspondence

**Comment by alazymeme** [comment]
How will your ban be reviewed if you don't provide a twitch username?
Not only this, but the likelihood of an unban is very low - not only that, but this is for bugs and issues with pajbot.

**Comment by pajlada** [comment]
Hey! This is not the right place to ask for an unban! You can DM me the details in Discord and I will get to it.
