### ISSUE TITLE
Modify settings with bot running

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#53]
!edit setting ban_ascii 1

**Comment by gigglearrows** [comment]
maby add a setting where you can choose that bot shall update the settings on the go or not.

**Comment by pajlada** [comment]
I'm closing this issue, because I'm moving away from keeping stuff in the tb_settings table.
I've moved to creating modules for small tasks instead, and each module can have custom settings which are modifiable via the web interface.
