### ISSUE TITLE
Idea. 1.Highlights 2.Livetweet 3.Bot Mod List 4.Motd List

### ISSUE THREAD

**Issue by Nacht123** [pajlada/pajbot#75]
__Some Idea's__

- [x] 1. Livetweet
- [x] 2. Bot Mod List
- [x] 3. Motd List

1. Highlights
- [x] Change the overview for highlights, get a better view of the comments. 
- [x] Disable the title from the stream, its 99% a stupid useless title
- [ ] Add a search box somewhere.
![highlights](http://i.imgur.com/bo6UFW1.png)

2.
Twitter Livefeed in the admin control
![twitter](http://i.imgur.com/1pOlCro.png)

3.
Overview Bot Mod's in the admin control
![mods](http://i.imgur.com/k4uy01m.png)

4.Motd
Change / Overview Motd in the admin control
level 1000 / or broadcaster or whitlisted mod if no level 1000 user there
![motd](http://i.imgur.com/4HWu3tf.png)

**Comment by gigglearrows** [comment]
yupp
