### ISSUE TITLE
Suggestions from Transcendence9

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#76]
- [x] Make it so mods have 80% cd reduction
- [x] Add a warning system to timeouts

For the web interface:
- [x] Add a "Back to command" link next to Save Changes on Edit Command
- [x] Create/Modify MOTDs (timed messages) #75 
- [x] Create/Modify Banphrases
- [x] Improve the alias on "create command" page.
- [x] Check what enter does in all fields on the Create Command page.
- [x] If no alias has been added, and Create is pressed, press Add Alias as well first.
- [ ] Move over eloise's dashboard

**Comment by Nacht123** [comment]
[ ]  Improve the alias on "edit command" page.
You can't edit aliases in the admin interface.

[ ] **Found a small bug** :bug: 
If you use copy and paste on __create a command__ for __aliases__,
you can create a command with spaces.
That command won't work, but it will be in the database.
