### ISSUE TITLE
Add Last.FM feature for spotify/youtube scrobbling

### ISSUE THREAD

**Issue by gigglearrows** [pajlada/pajbot#88]
code in this link https://gist.github.com/gigglearrows/e90aa2dce969f3871c31

note that it is implemented in an older tyggbot version.
I can edit it later once I've updated anniesbot fully

**Comment by pajlada** [comment]
Fixed in 9d589108b26b1196c3b351cd50d40a7caa0fdeba from your pull request.
Thanks!
