### ISSUE TITLE
Show streamers game information on website

### ISSUE THREAD

**Issue by Hanswurstus** [pajlada/pajbot#92]
It would be a nice feature to show the current game information (if in game then the name of the game) of each streamer on their homepage. I will only cover steam games here. (In the future it would obviously be nice to extend it to also show the current battle.net game)

I found two possibilities: 

* It makes sense to use the steam API for this. You need an API key though. The advantage is, that you can also get it as json and you could also do a lot of other stuff with the steam API. That would look like this:
http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&steamids=76561198040681843
This is definitely the best method to use.
 * If the user is in game, the json will contain a key called **gameextrainfo**, its value is the name of the game the user is currently playing. If the user is not in game that key doesn't exist.

* Just to give you another possibility, you can also get the game information using xml. It doesn't require an API key or anything else. That would look like this: 
http://steamcommunity.com/profiles/76561198040681843/?xml=1 
(or if the user has a custom steam id like this: http://steamcommunity.com/id/hanswurstus/?xml=1 but I don't recommend using it since it's less reliable.)
 * The **stateMessage** tag contains the game information of the user. ('Online' when user online but not in game, 'In-Game\<br/>Game Name' when in game. No idea why there is the \<br/> but it just is)

**Comment by Nacht123** [comment]
You can **already** see the Game on the **frontpage**, without the steam api.
That was the **basic idea** that you wanted. For **ingame stats** just **watch the stream** :eyes: 

If the streamer changes the game on twitch it will be always the right game :cactus: 

Done here 307c14dc9a09fe45a6ca325e0d5dbcc17767ecf7 and here 7036ba8db232e31bd360150dfd17f09dedba833d
