### ISSUE TITLE
Emote quiz

### ISSUE THREAD

**Issue by hptk** [pajlada/pajbot#98]
So this here api
http://twitchemotes.com/api_cache/v2/global.json
the returned list also cintains explanations for emotes, examples:
* This is the face of famous Starcraft 2 player, EG.Suppy
* This is the face of Justin Kan, co-founder of Justin.tv and Twitch.

The idea is for the bot to say the description and ask "what emote are we talking about??", chat spams and geusses (either plain spam like the bingo or with !answer or something). The bot can ask periodically or upon a command like !emotequiz

I think this can raise awareness about emotes and what they are from and for.

**Comment by Nacht123** [comment]
I would say this is a bit too easy to win.

And people can make a bot to win it.

**Comment by pajlada** [comment]
I agree with @Nacht123 on this one.
This is stuff that's only fun if new content is added regularly, but that's a bit too tryhard for a feature this "fun"
